// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trivia-vibes/ApresMidnight.tsx": () => import("../components/mockups/trivia-vibes/ApresMidnight.tsx"),
  "./components/mockups/trivia-vibes/ArcadeRush.tsx": () => import("../components/mockups/trivia-vibes/ArcadeRush.tsx"),
  "./components/mockups/trivia-vibes/CleanSlate.tsx": () => import("../components/mockups/trivia-vibes/CleanSlate.tsx")
};
