import path from 'path';
import { readFileSync, readdirSync } from 'fs';
import { sql } from 'drizzle-orm';
import { db } from '../db';

// 0000 was generated by drizzle-kit and is already applied by `db:push`.
// Bootstrap it as pre-applied so the runner never tries to execute it directly.
const BOOTSTRAP_MIGRATION = '0000_daffy_malcolm_colcord.sql';

export async function runMigrations(): Promise<void> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS _sql_migrations (
      filename TEXT PRIMARY KEY,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  // Mark the Drizzle-generated schema file as already applied without running it —
  // db:push handles the initial schema so re-running 0000 would fail on existing tables.
  await db.execute(sql`
    INSERT INTO _sql_migrations (filename)
    VALUES (${BOOTSTRAP_MIGRATION})
    ON CONFLICT DO NOTHING
  `);

  const result = await db.execute<{ filename: string }>(sql`SELECT filename FROM _sql_migrations`);
  const applied = new Set(result.rows.map((r) => r.filename));

  const migrationsDir = path.resolve(process.cwd(), 'migrations');
  const files = readdirSync(migrationsDir)
    .filter((f) => f.endsWith('.sql'))
    .sort();

  for (const file of files) {
    if (applied.has(file)) continue;

    const content = readFileSync(path.join(migrationsDir, file), 'utf-8');
    await db.transaction(async (tx) => {
      await tx.execute(sql.raw(content));
      await tx.execute(sql`INSERT INTO _sql_migrations (filename) VALUES (${file})`);
    });
    console.log(`[migrate] Applied: ${file}`);
  }
}
