import path from 'path';
import { readFileSync, readdirSync } from 'fs';
import { pool } from '../db';

// 0000 was generated by drizzle-kit and is already applied by `db:push`.
// Bootstrap it as pre-applied so the runner never tries to execute it directly.
const BOOTSTRAP_MIGRATION = '0000_daffy_malcolm_colcord.sql';

// Fixed lock ID for this app's migration runner.
const MIGRATION_LOCK_ID = 8_753_210;

export async function runMigrations(): Promise<void> {
  // Check out one dedicated connection so pg_advisory_lock and pg_advisory_unlock
  // are guaranteed to run on the same DB session. Using a Pool-backed db.execute()
  // could dispatch each call to a different physical connection — the lock and
  // unlock would then be on different sessions, leaving the lock permanently held
  // on an idle pooled connection and not serializing concurrent callers at all.
  //
  // All migration work (DDL, reads, per-file transactions) also goes through this
  // single client so that the advisory lock actually covers the critical section.
  const client = await pool.connect();

  // Track whether the lock was acquired so the finally block can decide whether
  // to attempt an unlock. If pg_advisory_lock() itself throws, there is no lock
  // to release and we must not call pg_advisory_unlock().
  let lockAcquired = false;

  try {
    await client.query('SELECT pg_advisory_lock($1)', [MIGRATION_LOCK_ID]);
    lockAcquired = true;

    await client.query(`
      CREATE TABLE IF NOT EXISTS _sql_migrations (
        filename TEXT PRIMARY KEY,
        applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // Mark the Drizzle-generated schema file as already applied without running it.
    // db:push handles the initial schema, so re-running 0000 would fail on existing tables.
    await client.query(
      `INSERT INTO _sql_migrations (filename) VALUES ($1) ON CONFLICT DO NOTHING`,
      [BOOTSTRAP_MIGRATION]
    );

    const { rows } = await client.query<{ filename: string }>(
      `SELECT filename FROM _sql_migrations`
    );
    const applied = new Set(rows.map((r) => r.filename));

    const migrationsDir = path.resolve(process.cwd(), 'migrations');
    const files = readdirSync(migrationsDir)
      .filter((f) => f.endsWith('.sql'))
      .sort();

    for (const file of files) {
      if (applied.has(file)) continue;

      const content = readFileSync(path.join(migrationsDir, file), 'utf-8');

      // Wrap each migration in its own transaction so a failure rolls back only
      // that file and does not affect previously-committed migrations.
      await client.query('BEGIN');
      try {
        await client.query(content);
        // ON CONFLICT DO NOTHING: belt-and-suspenders in case a manual run or
        // future refactor bypasses the advisory lock and races to this point.
        await client.query(
          `INSERT INTO _sql_migrations (filename) VALUES ($1) ON CONFLICT DO NOTHING`,
          [file]
        );
        await client.query('COMMIT');
      } catch (migErr) {
        // Ignore rollback errors (e.g. broken connection) — the original error
        // is what callers need to see.
        await client.query('ROLLBACK').catch(() => {});
        throw migErr;
      }

      console.log(`[migrate] Applied: ${file}`);
    }
  } finally {
    if (lockAcquired) {
      try {
        await client.query('SELECT pg_advisory_unlock($1)', [MIGRATION_LOCK_ID]);
        client.release();
      } catch {
        // Unlock failed (likely a broken connection). Destroy this client so the
        // pool never hands it out again. PostgreSQL automatically releases
        // session-level advisory locks when the session ends, so the lock will
        // not stay stuck.
        client.release(true);
      }
    } else {
      client.release();
    }
  }
}
